### ISSUE TITLE
determine set level metadata

### ISSUE THREAD

**Issue by ect123** [ubc-lib-geo/map-o-matic#1]
Set level metadata populates each `map-item` page's front matter and should include all of the appropriate metadata to describe the set of maps. Most of this information could come from the Library's set-level catalogue record, for example: [http://resolve.library.ubc.ca/cgi-bin/catsearch?bid=3194411](http://resolve.library.ubc.ca/cgi-bin/catsearch?bid=3194411).

Descriptive
- **Title** [Doesn't have to be verbatim from catalog record]
- **Publisher**
- **Scale**
- **Series Number**
- **Web URL** [a web link to additional information - not catalog record]
- **Complete** [Y/N for completeness]
- **Type** [maps or aerial photos]

Physical Location
- **Library Location** 
- **Call Number**
- **Catalog URL** [a permalink to catalog record]    

Sort/Filter  
- **Geographic Location** [Country or State/Province] 
- **First Year**
- **Last Year**

**Comment by nickmmurphy** [comment]
Set level metadata has been determined and added to README.md documentation. This can be revisited if necessary, but for now the issue has been completed.
