### ISSUE TITLE
Metadata values under incorrect elements 

### ISSUE THREAD

**Issue by nickmmurphy** [ubc-lib-geo/map-o-matic#10]
The table displays metadata values in the wrong categories. For example, the image below shows maps with notes on physical condition under the year of publication. 
![image](https://user-images.githubusercontent.com/97468353/197632940-c12b4905-a0c6-4e58-87b6-3e51a8807ca6.png)

**Comment by laurenholzman** [comment]
The accordion display I've been working on with Evan gets rid of this (by extension because there's no more table). Not sure if this is helpful for you or not.

**Comment by nickmmurphy** [comment]
> The accordion display I've been working on with Evan gets rid of this (by extension because there's no more table). Not sure if this is helpful for you or not.

You are correct, my mistake!
