### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by ect123** [ubc-lib-geo/map-o-matic#3]
Right now the landing page is just an introduction to the project and a link to a demo. We'll need a more usable page that describes very briefly what this site is as well as a very easy way to get started finding indexes.

**Comment by ect123** [comment]
A new site variable should be added to `_config.yml` to indicate the name of the directory being sued to store each map item .md file (e.g. `indexDirectory`). Once that's created, then I think the following Liquid snippet will list all published map pages with H1 titles (as long as pages have a titles):

```
{% assign pages = site.pages | where_exp: 'page', 'page.title' %}
{% for page in pages %}
    <div>
       <h1><a href="{{ site.url }}{{ site.baseurl }}{{ site.indexDirectory }}/{{ page.slug }}">{{page.title}}</a></h1>
    </div>
{% endfor %}
```
Other page variables could be added if needed, but I'm unsure what might be useful (location? number of sheets? date range?).

**Comment by ect123** [comment]
The current index.md page can be replaced with any new landing page content, which in turn will mean we should also create an "about" page. That will be a separate issue

**Comment by nickmmurphy** [comment]
The landing page has the list of current indexes on it as well as a brief description of the site. Other functionalities can be added under future issues, but this one is complete.
