### ISSUE TITLE
Improve language for "more info" button

### ISSUE THREAD

**Issue by ect123** [ubc-lib-geo/map-o-matic#41]
Users are unsure what sort of info this might be.

**Comment by nickmmurphy** [comment]
@ect123 Here are some options I've thought of:

- Go to Catalogue Listing
- Open Catalogue
- View Map Set Record
- View Item in Catalogue
- Open Map Set Record

Do any of these stand out as better?

**Comment by ect123** [comment]
Let's go with Open Catalogue. Thanks!
