### ISSUE TITLE
spacing after scale when there is no scale

### ISSUE THREAD

**Issue by ect123** [ubc-lib-geo/map-o-matic#51]
Without a `scale` value in the .md file for a map set, the info pill at the top of the page applies a space after the word "scale" but there is no padding.

**Comment by nickmmurphy** [comment]
Added scale to the set bc-gvrd.md, which was the only map with the spacing issue. "Scale" is defined in our set-level metadata table as a required value, so there should always be something put there, even if that is just the word "Varies". The issue should not repeat as long as there is always a required scale value in each markdown file.
