### ISSUE TITLE
replace table showing metadata

### ISSUE THREAD

**Issue by ect123** [ubc-lib-geo/map-o-matic#8]
Right now the table showing sheet level OIM metadata is a bit unreadable, so it would be good to have something that was more user-friendly. We chatted about an accordion list. The main items that should be visible before the accordion is opened are:
- label
- title
- datePub

If there could also be a button to any URLs pointing to digital images (webUrl)

The open accordion could be everything else.

**Comment by nickmmurphy** [comment]
@thehellomartian has completed the accordion and pushed to develop.
